spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    uasename: root
    password: root
    url: jdbc:mysql://localhost:3306/wechat_order?characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
  server:
    context-path: /wechat




wechat:
  mpAppId: ?
  mpAppSecret: ?
  openAppId: ?
  openAppSecret: ?
  mchId: ?
  mchKey: ?
  keyPath: ?
  notifyUrl: ?
  templateId:
    orderStatus: ?

projectUrl:
  wechatMpAuthorize: ?
  wechatOpenAuthorize: ?
  sell: ?

logging:
  level:
    com.schuke.mapper：trace
mybatis:
  mapper-locations: classpath:mapper/*.xml